[package]
authors = ["Satoshi Amemiya <satoshi_amemiya@voyagegroup.com>"]
name = "kntn"
version = "0.2.0"

[dependencies]
getopts = "0.2.15"
handlebars = "0.30.0-beta.4"
rand = "0.4.1"
serde_json = "1.0.8"
